# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  schedule:
    # Every day at 9:00 UTC/5:00 ET
    - cron:  '0 9 * 1,2,9-12 *'

name: Release-ESPN-QBR

jobs:
  update:
    name: update_qbr
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            jthomasmock/espnscrapeR
            nflverse/nflverse-data
            nflverse/nflreadr
            ropensci/piggyback
            purrr
            tidyr
            tibble

      - name: Update QBR
        run: Rscript -e 'source("auto/update_qbr.R")'

      # REMOVE THIS AFTER THE 2023 SEASON!
      - name: Commit updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data
          git commit -m "Automated QBR stats updates `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
