on:
  workflow_dispatch:
  schedule:
    # Every day at 9:00 UTC/5:00 ET
    - cron:  '0 9 * 1,2,9-12 *'

name: Release-ESPN-QBR

jobs:
  update:
    name: update_qbr
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            jthomasmock/espnscrapeR
            nflverse/nflverse-data
            nflverse/nflreadr
            purrr
            tidyr
            tibble

      - name: Update QBR
        run: Rscript -e 'source("auto/update_qbr.R")'
