on:
  schedule:
    # runs every tuesday at 11:00 AM UTC in Jan, Feb, Sep-Dec
    - cron:  '0 11 * 1,2,9-12 4'
  workflow_dispatch:

name: Update PFR Adv Stats

jobs:
  update:
    name: Update Data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pak(c("jthomasmock/espnscrapeR"), dependencies = TRUE)
          pak::pak(c("tidyverse", "glue", "rvest", "janitor"))
        shell: Rscript {0}

      - name: Update Advanced Stats
        run: Rscript -e 'source("R/scrape-adv.R")'

      - name: Commit updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated Adv stats updates `date`" || echo "No changes to commit"
