on:
  schedule:
    # runs every tuesday at 11:00 AM UTC in Jan, Feb, Sep-Dec
    - cron:  '0 11 * 1,2,9-12 2'
  workflow_dispatch:

name: Update QBR, FPI, and Win Rate Stats

jobs:
  update:
    name: Update Data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          install.packages(c("tidyverse", "remotes", "glue", "rvest", "janitor"))
          remotes::install_github("jthomasmock/espnscrapeR")
        shell: Rscript {0}

      - name: Update QBR
        run: Rscript -e 'source("R/qbr.R")'

      - name: Commit updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated QBR stats updates `date`" || echo "No changes to commit"

      - name: Update FPI
        run: Rscript -e 'source("R/scrape-fpi.R")'

      - name: Commit updated data
        run: |
          git pull
          git add data
          git commit -m "Automated FPI data updates `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"

      - name: Update WinRate
        run: Rscript -e 'source("R/scrape-winrate.R")'

      - name: Commit updated data
        run: |
          git pull
          git add data
          git commit -m "Automated ESPN WinRate data updates `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
